# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.
twitter_app: &twitter_app
  consumer_key: 43lJXf0PHv6MZkNjNs2aXLoCi
  consumer_secret: H2ev2hwLkSahtdvD4hbBdtSOZJzd72455PIiGzfiBGVGgzTlE3

development:
  secret_key_base: 01f0aa86d8ec57ba6701b150554370fd44301f2bb740c1985d9e36a46e16548d839ed8d9b8e28bf785299778575b037529db06a689c85f640c1e459229c738c4
  twitter_app:
    <<: *twitter_app

test:
  secret_key_base: 3a4ebc0a25821f9ae58923e275cb2633fde5eb4eed4e8d0f14647d193ed2a7088c0f5852e9c2e1a823869827d32e5f34da963e0e22405ee534d2accb97670fcd
  twitter_app:
    <<: *twitter_app


production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_app:
    consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
    consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
